// Survey Feedback data — parsed from Google Sheet (Parents Feedback)
// Sheets: JPS, Tattva, Siddhanta, Arkere, Marathalli, HSR, Oragadam, Dindigul

export const SURVEY_DATA = {
  JPS: {
    label: 'JPS Report',
    cocurricular: [
      { name: 'Dance & Movement', count: 33, pct: 21.02 },
      { name: 'Art & Craft', count: 32, pct: 20.38 },
      { name: 'Storytelling', count: 31, pct: 19.75 },
      { name: 'Music & Rhythm', count: 24, pct: 15.29 },
      { name: 'DIY & Craft', count: 21, pct: 13.38 },
      { name: 'Gardening', count: 16, pct: 10.19 },
    ],
    academicFocus: [
      { name: 'Confidence & Expression', count: 42, pct: 32.81 },
      { name: 'Language Development', count: 38, pct: 29.69 },
      { name: 'Learning Through Play', count: 32, pct: 25.00 },
      { name: 'Early Numeracy', count: 16, pct: 12.50 },
    ],
    areasOfImprovement: [
      { name: 'Activity-Based Learning', count: 39, pct: 36.11 },
      { name: 'Individual Attention', count: 27, pct: 25.00 },
      { name: 'Teaching Approach', count: 15, pct: 13.89 },
      { name: 'Classroom Discipline', count: 14, pct: 12.96 },
      { name: 'Communication w/ Parents', count: 13, pct: 12.04 },
    ],
    satisfactionAreas: [
      { area: 'Student Motivation', count: 68, pct: 24.29 },
      { area: 'Teaching Quality', count: 62, pct: 22.14 },
      { area: 'Homework & Practice', count: 57, pct: 20.36 },
      { area: 'Doubt-Solving', count: 54, pct: 19.29 },
      { area: 'Assessments & Feedback', count: 39, pct: 13.93 },
    ],
    gradeSatisfaction: [
      { grade: 'Grade 1', academic: 3.24, teaching: 3.21, gaps: 3.12 },
      { grade: 'Grade 2', academic: 3.94, teaching: 3.89, gaps: 3.94 },
      { grade: 'Grade 3', academic: 3.47, teaching: 3.53, gaps: 3.40 },
      { grade: 'Grade 4', academic: 3.41, teaching: 3.45, gaps: 3.23 },
      { grade: 'Grade 5', academic: 3.47, teaching: 3.35, gaps: 3.19 },
    ],
    subjects: [
      { name: 'Mathematics', count: 16, pct: 28.57 },
      { name: 'Science', count: 14, pct: 25.00 },
      { name: 'Languages', count: 14, pct: 25.00 },
      { name: 'English', count: 12, pct: 21.43 },
    ],
    activities: [
      { name: 'Sports', count: 40, pct: 37.04 },
      { name: 'Dance', count: 26, pct: 24.07 },
      { name: 'Music', count: 22, pct: 20.37 },
      { name: 'Theatre', count: 20, pct: 18.52 },
    ],
    remarks: [
      { name: 'None / Satisfied', count: 68, pct: 61.82 },
      { name: 'Teaching Quality', count: 15, pct: 13.64 },
      { name: 'Teaching Methodology', count: 9, pct: 8.18 },
      { name: 'Hygiene', count: 4, pct: 3.64 },
      { name: 'Individual Attention', count: 3, pct: 2.73 },
      { name: 'Progress Tracking', count: 5, pct: 4.55 },
      { name: 'Academic Focus', count: 2, pct: 1.82 },
      { name: 'Fees', count: 2, pct: 1.82 },
      { name: 'Extra-curricular', count: 1, pct: 0.91 },
      { name: 'Want In-Person Meeting', count: 1, pct: 0.91 },
    ],
    ppG6G8: {
      total: 35,
      teacherKnowledge: [{ r: 1, n: 3 }, { r: 2, n: 5 }, { r: 3, n: 13 }, { r: 4, n: 8 }, { r: 5, n: 6 }],
      doubtSolving:     [{ r: 1, n: 4 }, { r: 2, n: 6 }, { r: 3, n: 11 }, { r: 4, n: 6 }, { r: 5, n: 8 }],
      academicRigor:    [{ r: 1, n: 4 }, { r: 2, n: 4 }, { r: 3, n: 15 }, { r: 4, n: 6 }, { r: 5, n: 6 }],
      nTagging: [
        { name: 'None', count: 12, pct: 34.29 }, { name: 'Teaching Quality', count: 8, pct: 22.86 },
        { name: 'Teaching Methodology', count: 6, pct: 17.14 }, { name: 'Academic Focus', count: 3, pct: 8.57 },
        { name: 'Individual Attention', count: 3, pct: 8.57 }, { name: 'Others', count: 1, pct: 2.86 },
        { name: 'Progress Tracking', count: 1, pct: 2.86 }, { name: 'Hygiene & Infra', count: 1, pct: 2.86 },
      ],
      improvements: [
        { name: 'Depth of Teaching', count: 11, pct: 31.43 }, { name: 'Study Discipline', count: 10, pct: 28.57 },
        { name: 'Assessments & Feedback', count: 8, pct: 22.86 }, { name: 'Exam Preparedness', count: 6, pct: 17.14 },
      ],
    },
  },

  Tattva: {
    label: 'Tattva Report',
    cocurricular: [
      { name: 'Music & Rhythm', count: 14, pct: 20.00 },
      { name: 'Dance & Movement', count: 12, pct: 17.14 },
      { name: 'Art & Craft', count: 11, pct: 15.71 },
      { name: 'Gardening', count: 11, pct: 15.71 },
      { name: 'Storytelling', count: 9, pct: 12.86 },
      { name: 'DIY & Craft', count: 8, pct: 11.43 },
      { name: 'Pottery', count: 5, pct: 7.14 },
    ],
    academicFocus: [
      { name: 'Confidence & Expression', count: 14, pct: 34.15 },
      { name: 'Learning Through Play', count: 14, pct: 34.15 },
      { name: 'Language Development', count: 9, pct: 21.95 },
      { name: 'Early Numeracy', count: 4, pct: 9.76 },
    ],
    areasOfImprovement: [
      { name: 'Activity-Based Learning', count: 11, pct: 32.35 },
      { name: 'Individual Attention', count: 9, pct: 26.47 },
      { name: 'Teaching Approach', count: 5, pct: 14.71 },
      { name: 'Communication w/ Parents', count: 5, pct: 14.71 },
      { name: 'Classroom Discipline', count: 4, pct: 11.76 },
    ],
    satisfactionAreas: [
      { area: 'Teaching Quality', count: 29, pct: 23.97 },
      { area: 'Student Motivation', count: 30, pct: 24.79 },
      { area: 'Doubt-Solving', count: 23, pct: 19.01 },
      { area: 'Homework & Practice', count: 20, pct: 16.53 },
      { area: 'Assessments & Feedback', count: 19, pct: 15.70 },
    ],
    gradeSatisfaction: [
      { grade: 'Grade 1', academic: 4.10, teaching: 4.20, gaps: 4.00 },
      { grade: 'Grade 2', academic: 4.00, teaching: 4.10, gaps: 4.10 },
      { grade: 'Grade 3', academic: 3.09, teaching: 3.09, gaps: 2.64 },
      { grade: 'Grade 4', academic: 3.17, teaching: 3.17, gaps: 2.33 },
      { grade: 'Grade 5', academic: 3.10, teaching: 2.91, gaps: 2.64 },
    ],
    subjects: [
      { name: 'Mathematics', count: 33, pct: 27.73 },
      { name: 'Science', count: 33, pct: 27.73 },
      { name: 'Languages', count: 31, pct: 26.05 },
      { name: 'English', count: 22, pct: 18.49 },
    ],
    activities: [
      { name: 'Sports', count: 44, pct: 40.00 },
      { name: 'Dance', count: 23, pct: 20.91 },
      { name: 'Music', count: 23, pct: 20.91 },
      { name: 'Theatre', count: 20, pct: 18.18 },
    ],
    remarks: [
      { name: 'None / Satisfied', count: 25, pct: 49.02 },
      { name: 'Teaching Quality', count: 8, pct: 15.69 },
      { name: 'Academic Focus', count: 6, pct: 11.76 },
      { name: 'Others', count: 6, pct: 11.76 },
      { name: 'Teaching Methodology', count: 5, pct: 9.80 },
      { name: 'Extra-curricular', count: 1, pct: 1.96 },
    ],
    ppG6G8: {
      total: 37,
      teacherKnowledge: [{ r: 1, n: 1 }, { r: 2, n: 7 }, { r: 3, n: 7 }, { r: 4, n: 15 }, { r: 5, n: 6 }],
      doubtSolving:     [{ r: 1, n: 2 }, { r: 2, n: 3 }, { r: 3, n: 9 }, { r: 4, n: 13 }, { r: 5, n: 10 }],
      academicRigor:    [{ r: 1, n: 1 }, { r: 2, n: 4 }, { r: 3, n: 10 }, { r: 4, n: 15 }, { r: 5, n: 8 }],
      nTagging: [
        { name: 'None', count: 24, pct: 63.16 }, { name: 'Teaching Methodology', count: 5, pct: 13.16 },
        { name: 'Individual Attention', count: 3, pct: 7.89 }, { name: 'Progress Tracking', count: 2, pct: 5.26 },
        { name: 'Teaching Quality', count: 2, pct: 5.26 }, { name: 'Academic Focus', count: 1, pct: 2.63 },
        { name: 'Others', count: 1, pct: 2.63 },
      ],
      improvements: [
        { name: 'Study Discipline', count: 20, pct: 33.90 }, { name: 'Exam Preparedness', count: 14, pct: 23.73 },
        { name: 'Depth of Teaching', count: 13, pct: 22.03 }, { name: 'Assessments & Feedback', count: 12, pct: 20.34 },
      ],
    },
    ppG9G12: {
      gradeSatisfaction: [
        { grade: 'Grade 9',  academic: 3.38, teaching: 3.00, gaps: 3.54 },
        { grade: 'Grade 10', academic: 3.00, teaching: 3.00, gaps: 3.00 },
        { grade: 'Grade 11', academic: 3.00, teaching: 3.00, gaps: 3.50 },
        { grade: 'Grade 12', academic: 3.00, teaching: 4.00, gaps: 4.00 },
      ],
      academicPriorities: [
        { name: 'Board Results', count: 14, pct: 27.45 }, { name: 'Concept Mastery', count: 13, pct: 25.49 },
        { name: 'Career Guidance', count: 14, pct: 27.45 }, { name: 'Competitive Exams', count: 10, pct: 19.61 },
      ],
      stemPrograms: [
        { name: 'Design Thinking', count: 18, pct: 38.30 }, { name: 'Robotics', count: 12, pct: 25.53 },
        { name: 'Advanced Coding', count: 9, pct: 19.15 }, { name: 'Portfolio Projects', count: 8, pct: 17.02 },
      ],
    },
  },

  Siddhanta: {
    label: 'Siddhanta Report',
    cocurricular: [
      { name: 'Music & Rhythm', count: 11, pct: 18.64 },
      { name: 'Dance & Movement', count: 10, pct: 16.95 },
      { name: 'Storytelling', count: 10, pct: 16.95 },
      { name: 'Art & Craft', count: 9, pct: 15.25 },
      { name: 'DIY & Craft', count: 9, pct: 15.25 },
      { name: 'Gardening', count: 7, pct: 11.86 },
      { name: 'Pottery', count: 3, pct: 5.08 },
    ],
    academicFocus: [
      { name: 'Confidence & Expression', count: 17, pct: 42.50 },
      { name: 'Language Development', count: 9, pct: 22.50 },
      { name: 'Learning Through Play', count: 8, pct: 20.00 },
      { name: 'Early Numeracy', count: 6, pct: 15.00 },
    ],
    areasOfImprovement: [
      { name: 'Individual Attention', count: 11, pct: 55.00 },
      { name: 'Activity-Based Learning', count: 7, pct: 35.00 },
      { name: 'Teaching Approach', count: 1, pct: 5.00 },
      { name: 'Classroom Discipline', count: 1, pct: 5.00 },
    ],
    satisfactionAreas: [
      { area: 'Student Motivation', count: 31, pct: 31.00 },
      { area: 'Homework & Practice', count: 20, pct: 20.00 },
      { area: 'Teaching Quality', count: 17, pct: 17.00 },
      { area: 'Assessments & Feedback', count: 17, pct: 17.00 },
      { area: 'Doubt-Solving', count: 15, pct: 15.00 },
    ],
    gradeSatisfaction: [
      { grade: 'Grade 1', academic: 4.11, teaching: 3.94, gaps: 4.00 },
      { grade: 'Grade 2', academic: 3.29, teaching: 3.29, gaps: 3.00 },
      { grade: 'Grade 3', academic: 3.90, teaching: 3.90, gaps: 3.70 },
      { grade: 'Grade 4', academic: 3.90, teaching: 3.90, gaps: 3.50 },
      { grade: 'Grade 5', academic: 4.18, teaching: 3.75, gaps: 3.58 },
    ],
    subjects: [
      { name: 'Mathematics', count: 36, pct: 31.30 },
      { name: 'Languages', count: 35, pct: 30.43 },
      { name: 'Science', count: 27, pct: 23.48 },
      { name: 'English', count: 17, pct: 14.78 },
    ],
    activities: [
      { name: 'Sports', count: 48, pct: 37.21 },
      { name: 'Music', count: 32, pct: 24.81 },
      { name: 'Dance', count: 29, pct: 22.48 },
      { name: 'Theatre', count: 20, pct: 15.50 },
    ],
    remarks: [
      { name: 'None / Satisfied', count: 47, pct: 72.31 },
      { name: 'Teaching Quality', count: 4, pct: 6.15 },
      { name: 'Academic Focus', count: 4, pct: 6.15 },
      { name: 'Teaching Methodology', count: 3, pct: 4.62 },
      { name: 'Extra-curricular', count: 2, pct: 3.08 },
      { name: 'Individual Attention', count: 2, pct: 3.08 },
      { name: 'Others', count: 3, pct: 4.62 },
    ],
    ppG6G8: {
      total: 5,
      teacherKnowledge: [{ r: 3, n: 1 }, { r: 4, n: 3 }, { r: 5, n: 1 }],
      doubtSolving:     [{ r: 3, n: 3 }, { r: 4, n: 1 }, { r: 5, n: 1 }],
      academicRigor:    [{ r: 3, n: 2 }, { r: 4, n: 1 }, { r: 5, n: 2 }],
      nTagging: [
        { name: 'None', count: 2, pct: 66.67 }, { name: 'Academic Focus', count: 1, pct: 33.33 },
      ],
      improvements: [
        { name: 'Depth of Teaching', count: 3, pct: 60.00 }, { name: 'Exam Preparedness', count: 2, pct: 40.00 },
      ],
    },
  },

  Arkere: {
    label: 'Arkere Report',
    cocurricular: [
      { name: 'Dance & Movement', count: 3, pct: 75.00 },
      { name: 'Storytelling', count: 1, pct: 25.00 },
      { name: 'Art & Craft', count: 0, pct: 0 },
      { name: 'DIY & Craft', count: 0, pct: 0 },
      { name: 'Music & Rhythm', count: 0, pct: 0 },
      { name: 'Gardening', count: 0, pct: 0 },
    ],
    academicFocus: [
      { name: 'Language Development', count: 2, pct: 50.00 },
      { name: 'Confidence & Expression', count: 1, pct: 25.00 },
      { name: 'Learning Through Play', count: 1, pct: 25.00 },
      { name: 'Early Numeracy', count: 0, pct: 0 },
    ],
    areasOfImprovement: [
      { name: 'Teaching Approach', count: 3, pct: 60.00 },
      { name: 'Activity-Based Learning', count: 1, pct: 20.00 },
      { name: 'Individual Attention', count: 1, pct: 20.00 },
      { name: 'Classroom Discipline', count: 0, pct: 0 },
      { name: 'Communication w/ Parents', count: 0, pct: 0 },
    ],
    satisfactionAreas: [
      { area: 'Student Motivation', count: 6, pct: 30.00 },
      { area: 'Assessments & Feedback', count: 6, pct: 30.00 },
      { area: 'Teaching Quality', count: 4, pct: 20.00 },
      { area: 'Homework & Practice', count: 4, pct: 20.00 },
    ],
    gradeSatisfaction: [
      { grade: 'Grade 1', academic: 3.75, teaching: 4.00, gaps: 3.00 },
      { grade: 'Grade 2', academic: 3.50, teaching: 4.00, gaps: 3.50 },
      { grade: 'Grade 3', academic: 4.29, teaching: 3.57, gaps: 3.57 },
      { grade: 'Grade 5', academic: 3.00, teaching: 3.00, gaps: 3.00 },
    ],
    subjects: [
      { name: 'Languages', count: 9, pct: 34.62 },
      { name: 'English', count: 8, pct: 30.77 },
      { name: 'Mathematics', count: 6, pct: 23.08 },
      { name: 'Science', count: 3, pct: 11.54 },
    ],
    activities: [
      { name: 'Sports', count: 11, pct: 47.83 },
      { name: 'Dance', count: 6, pct: 26.09 },
      { name: 'Music', count: 5, pct: 21.74 },
      { name: 'Theatre', count: 1, pct: 4.35 },
    ],
    remarks: [
      { name: 'None / Satisfied', count: 10, pct: 71.43 },
      { name: 'Individual Attention', count: 2, pct: 14.29 },
      { name: 'Others', count: 2, pct: 14.29 },
    ],
    ppG6G8: {
      total: 30,
      teacherKnowledge: [{ r: 2, n: 1 }, { r: 3, n: 3 }, { r: 4, n: 2 }, { r: 5, n: 2 }],
      doubtSolving:     [{ r: 3, n: 3 }, { r: 4, n: 4 }, { r: 5, n: 1 }],
      academicRigor:    [{ r: 2, n: 2 }, { r: 3, n: 3 }, { r: 4, n: 20 }, { r: 5, n: 5 }],
      nTagging: [
        { name: 'None', count: 4, pct: 50.00 }, { name: 'Teaching Methodology', count: 3, pct: 37.50 },
        { name: 'Communication & Presentation', count: 1, pct: 12.50 },
      ],
      improvements: [
        { name: 'Depth of Teaching', count: 5, pct: 41.67 }, { name: 'Assessments & Feedback', count: 4, pct: 33.33 },
        { name: 'Study Discipline', count: 3, pct: 25.00 },
      ],
    },
  },

  Marathalli: {
    label: 'Marathalli Report',
    cocurricular: [
      { name: 'Art & Craft', count: 3, pct: 33.33 },
      { name: 'Dance & Movement', count: 3, pct: 33.33 },
      { name: 'Storytelling', count: 3, pct: 33.33 },
      { name: 'DIY & Craft', count: 0, pct: 0 },
      { name: 'Music & Rhythm', count: 0, pct: 0 },
      { name: 'Gardening', count: 0, pct: 0 },
    ],
    academicFocus: [
      { name: 'Learning Through Play', count: 4, pct: 36.36 },
      { name: 'Confidence & Expression', count: 3, pct: 27.27 },
      { name: 'Language Development', count: 3, pct: 27.27 },
      { name: 'Early Numeracy', count: 1, pct: 9.09 },
    ],
    areasOfImprovement: [
      { name: 'Activity-Based Learning', count: 3, pct: 30.00 },
      { name: 'Individual Attention', count: 3, pct: 30.00 },
      { name: 'Teaching Approach', count: 3, pct: 30.00 },
      { name: 'Classroom Discipline', count: 1, pct: 10.00 },
      { name: 'Communication w/ Parents', count: 0, pct: 0 },
    ],
    satisfactionAreas: [
      { area: 'Student Motivation', count: 23, pct: 23.23 },
      { area: 'Teaching Quality', count: 21, pct: 21.21 },
      { area: 'Doubt-Solving', count: 19, pct: 19.19 },
      { area: 'Homework & Practice', count: 18, pct: 18.18 },
      { area: 'Assessments & Feedback', count: 18, pct: 18.18 },
    ],
    gradeSatisfaction: [
      { grade: 'Grade 1', academic: 4.00, teaching: 4.00, gaps: 4.00 },
      { grade: 'Grade 2', academic: 3.50, teaching: 4.00, gaps: 3.00 },
      { grade: 'Grade 3', academic: 3.00, teaching: 3.00, gaps: 2.00 },
      { grade: 'Grade 4', academic: 3.50, teaching: 3.33, gaps: 3.00 },
      { grade: 'Grade 5', academic: 3.00, teaching: 3.00, gaps: 2.00 },
    ],
    academicPriorities: [
      { name: 'Strong Math & Science', count: 23, pct: 28.75 },
      { name: 'Concept Clarity', count: 22, pct: 27.50 },
      { name: 'English Communication', count: 21, pct: 26.25 },
      { name: 'Regular Assessments', count: 14, pct: 17.50 },
    ],
    subjects: [
      { name: 'Mathematics', count: 21, pct: 27.63 },
      { name: 'Science', count: 19, pct: 25.00 },
      { name: 'Languages', count: 20, pct: 26.32 },
      { name: 'English', count: 16, pct: 21.05 },
    ],
    activities: [
      { name: 'Sports', count: 25, pct: 37.88 },
      { name: 'Dance', count: 19, pct: 28.79 },
      { name: 'Music', count: 13, pct: 19.70 },
      { name: 'Theatre', count: 9, pct: 13.64 },
    ],
    remarks: [
      { name: 'None / Satisfied', count: 12, pct: 41.38 },
      { name: 'Teaching Quality', count: 7, pct: 24.14 },
      { name: 'Teaching Methodology', count: 5, pct: 17.24 },
      { name: 'Extra-curricular', count: 2, pct: 6.90 },
      { name: 'Individual Attention', count: 1, pct: 3.45 },
      { name: 'Hygiene & Infra', count: 1, pct: 3.45 },
      { name: 'Others', count: 1, pct: 3.45 },
    ],
    ppG6G8: {
      total: 35,
      teacherKnowledge: [{ r: 1, n: 3 }, { r: 2, n: 5 }, { r: 3, n: 13 }, { r: 4, n: 8 }, { r: 5, n: 6 }],
      doubtSolving:     [{ r: 1, n: 4 }, { r: 2, n: 6 }, { r: 3, n: 11 }, { r: 4, n: 6 }, { r: 5, n: 8 }],
      academicRigor:    [{ r: 1, n: 4 }, { r: 2, n: 4 }, { r: 3, n: 15 }, { r: 4, n: 6 }, { r: 5, n: 6 }],
      nTagging: [
        { name: 'None', count: 12, pct: 34.29 }, { name: 'Teaching Quality', count: 8, pct: 22.86 },
        { name: 'Teaching Methodology', count: 6, pct: 17.14 }, { name: 'Academic Focus', count: 3, pct: 8.57 },
        { name: 'Individual Attention', count: 3, pct: 8.57 }, { name: 'Progress Tracking', count: 1, pct: 2.86 },
        { name: 'Hygiene & Infra', count: 1, pct: 2.86 }, { name: 'Others', count: 1, pct: 2.86 },
      ],
      improvements: [
        { name: 'Depth of Teaching', count: 11, pct: 31.43 }, { name: 'Study Discipline', count: 10, pct: 28.57 },
        { name: 'Assessments & Feedback', count: 8, pct: 22.86 }, { name: 'Exam Preparedness', count: 6, pct: 17.14 },
      ],
    },
  },

  HSR: {
    label: 'HSR Report',
    cocurricular: [
      { name: 'Dance & Movement', count: 33, pct: 21.02 },
      { name: 'Art & Craft', count: 32, pct: 20.38 },
      { name: 'Storytelling', count: 31, pct: 19.75 },
      { name: 'Music & Rhythm', count: 24, pct: 15.29 },
      { name: 'DIY & Craft', count: 21, pct: 13.38 },
      { name: 'Gardening', count: 16, pct: 10.19 },
    ],
    academicFocus: [
      { name: 'Confidence & Expression', count: 42, pct: 32.81 },
      { name: 'Language Development', count: 38, pct: 29.69 },
      { name: 'Learning Through Play', count: 32, pct: 25.00 },
      { name: 'Early Numeracy', count: 16, pct: 12.50 },
    ],
    areasOfImprovement: [
      { name: 'Activity-Based Learning', count: 39, pct: 36.11 },
      { name: 'Individual Attention', count: 27, pct: 25.00 },
      { name: 'Teaching Approach', count: 15, pct: 13.89 },
      { name: 'Classroom Discipline', count: 14, pct: 12.96 },
      { name: 'Communication w/ Parents', count: 13, pct: 12.04 },
    ],
    satisfactionAreas: [
      { area: 'Student Motivation', count: 36, pct: 26.09 },
      { area: 'Teaching Quality', count: 27, pct: 19.57 },
      { area: 'Homework & Practice', count: 27, pct: 19.57 },
      { area: 'Doubt-Solving', count: 26, pct: 18.84 },
      { area: 'Assessments & Feedback', count: 22, pct: 15.94 },
    ],
    gradeSatisfaction: [
      { grade: 'Grade 1', academic: 3.83, teaching: 4.00, gaps: 4.00 },
      { grade: 'Grade 2', academic: 3.09, teaching: 3.30, gaps: 3.20 },
      { grade: 'Grade 3', academic: 3.42, teaching: 3.42, gaps: 3.25 },
      { grade: 'Grade 4', academic: 3.37, teaching: 3.58, gaps: 3.37 },
      { grade: 'Grade 5', academic: 3.70, teaching: 3.70, gaps: 3.60 },
    ],
    academicPriorities: [
      { name: 'Strong Math & Science', count: 21, pct: 30.00 },
      { name: 'Concept Clarity', count: 19, pct: 27.14 },
      { name: 'English Communication', count: 17, pct: 24.29 },
      { name: 'Regular Assessments', count: 13, pct: 18.57 },
    ],
    subjects: [
      { name: 'Mathematics', count: 16, pct: 28.57 },
      { name: 'Science', count: 14, pct: 25.00 },
      { name: 'Languages', count: 14, pct: 25.00 },
      { name: 'English', count: 12, pct: 21.43 },
    ],
    activities: [
      { name: 'Sports', count: 40, pct: 37.04 },
      { name: 'Dance', count: 26, pct: 24.07 },
      { name: 'Music', count: 22, pct: 20.37 },
      { name: 'Theatre', count: 20, pct: 18.52 },
    ],
    remarks: [
      { name: 'None / Satisfied', count: 68, pct: 61.82 },
      { name: 'Teaching Quality', count: 15, pct: 13.64 },
      { name: 'Teaching Methodology', count: 9, pct: 8.18 },
      { name: 'Individual Attention', count: 3, pct: 2.73 },
      { name: 'Hygiene', count: 4, pct: 3.64 },
      { name: 'Progress Tracking', count: 5, pct: 4.55 },
      { name: 'Academic Focus', count: 2, pct: 1.82 },
      { name: 'Fees', count: 2, pct: 1.82 },
      { name: 'Extra-curricular', count: 1, pct: 0.91 },
      { name: 'Want In-Person Meeting', count: 1, pct: 0.91 },
    ],
    ppG6G8: {
      total: 35,
      teacherKnowledge: [{ r: 1, n: 3 }, { r: 2, n: 5 }, { r: 3, n: 13 }, { r: 4, n: 8 }, { r: 5, n: 6 }],
      doubtSolving:     [{ r: 1, n: 4 }, { r: 2, n: 6 }, { r: 3, n: 11 }, { r: 4, n: 6 }, { r: 5, n: 8 }],
      academicRigor:    [{ r: 1, n: 4 }, { r: 2, n: 4 }, { r: 3, n: 15 }, { r: 4, n: 6 }, { r: 5, n: 6 }],
      nTagging: [
        { name: 'None', count: 12, pct: 34.29 }, { name: 'Teaching Quality', count: 8, pct: 22.86 },
        { name: 'Teaching Methodology', count: 6, pct: 17.14 }, { name: 'Academic Focus', count: 3, pct: 8.57 },
        { name: 'Individual Attention', count: 3, pct: 8.57 }, { name: 'Progress Tracking', count: 1, pct: 2.86 },
        { name: 'Hygiene & Infra', count: 1, pct: 2.86 }, { name: 'Others', count: 1, pct: 2.86 },
      ],
      improvements: [
        { name: 'Depth of Teaching', count: 11, pct: 31.43 }, { name: 'Study Discipline', count: 10, pct: 28.57 },
        { name: 'Assessments & Feedback', count: 8, pct: 22.86 }, { name: 'Exam Preparedness', count: 6, pct: 17.14 },
      ],
    },
  },

  Oragadam: {
    label: 'Oragadam Report',
    cocurricular: [
      { name: 'Storytelling', count: 27, pct: 22.13 },
      { name: 'Dance & Movement', count: 25, pct: 20.49 },
      { name: 'Music & Rhythm', count: 20, pct: 16.39 },
      { name: 'Art & Craft', count: 17, pct: 13.93 },
      { name: 'Gardening', count: 13, pct: 10.66 },
      { name: 'DIY & Craft', count: 12, pct: 9.84 },
      { name: 'Pottery', count: 8, pct: 6.56 },
    ],
    academicFocus: [
      { name: 'Confidence & Expression', count: 29, pct: 35.80 },
      { name: 'Language Development', count: 26, pct: 32.10 },
      { name: 'Learning Through Play', count: 14, pct: 17.28 },
      { name: 'Early Numeracy', count: 12, pct: 14.81 },
    ],
    areasOfImprovement: [
      { name: 'Communication w/ Parents', count: 20, pct: 31.25 },
      { name: 'Individual Attention', count: 18, pct: 28.13 },
      { name: 'Activity-Based Learning', count: 14, pct: 21.88 },
      { name: 'Classroom Discipline', count: 6, pct: 9.38 },
      { name: 'Teaching Approach', count: 6, pct: 9.38 },
    ],
    satisfactionAreas: [
      { area: 'Student Motivation', count: 36, pct: 28.35 },
      { area: 'Teaching Quality', count: 28, pct: 22.05 },
      { area: 'Homework & Practice', count: 23, pct: 18.11 },
      { area: 'Doubt-Solving', count: 20, pct: 15.75 },
      { area: 'Assessments & Feedback', count: 20, pct: 15.75 },
    ],
    gradeSatisfaction: [
      { grade: 'Grade 1', academic: 3.60, teaching: 3.33, gaps: 3.20 },
      { grade: 'Grade 2', academic: 3.64, teaching: 3.59, gaps: 3.50 },
      { grade: 'Grade 3', academic: 2.83, teaching: 2.33, gaps: 3.00 },
      { grade: 'Grade 4', academic: 3.00, teaching: 3.50, gaps: 3.00 },
      { grade: 'Grade 5', academic: 2.50, teaching: 1.50, gaps: 1.00 },
    ],
    subjects: [
      { name: 'Mathematics', count: 43, pct: 34.68 },
      { name: 'Science', count: 29, pct: 23.39 },
      { name: 'Languages', count: 26, pct: 20.97 },
      { name: 'English', count: 26, pct: 20.97 },
    ],
    activities: [
      { name: 'Sports', count: 44, pct: 38.60 },
      { name: 'Dance', count: 27, pct: 23.68 },
      { name: 'Music', count: 22, pct: 19.30 },
      { name: 'Theatre', count: 21, pct: 18.42 },
    ],
    remarks: [
      { name: 'None / Satisfied', count: 14, pct: 28.00 },
      { name: 'Academic Focus', count: 6, pct: 12.00 },
      { name: 'Teaching Methodology', count: 7, pct: 14.00 },
      { name: 'Teaching Quality', count: 9, pct: 18.00 },
      { name: 'Extra-curricular', count: 3, pct: 6.00 },
      { name: 'Individual Attention', count: 3, pct: 6.00 },
      { name: 'Communication & Presentation', count: 2, pct: 4.00 },
      { name: 'Progress Tracking', count: 1, pct: 2.00 },
      { name: 'Hygiene & Infra', count: 1, pct: 2.00 },
      { name: 'Others', count: 4, pct: 8.00 },
    ],
    ppG6G8: {
      total: 14,
      teacherKnowledge: [{ r: 2, n: 2 }, { r: 3, n: 4 }, { r: 4, n: 7 }, { r: 5, n: 1 }],
      doubtSolving:     [{ r: 2, n: 3 }, { r: 3, n: 3 }, { r: 4, n: 7 }, { r: 5, n: 1 }],
      academicRigor:    [{ r: 1, n: 1 }, { r: 3, n: 4 }, { r: 4, n: 9 }],
      nTagging: [
        { name: 'Teaching Quality', count: 5, pct: 35.71 }, { name: 'None', count: 4, pct: 28.57 },
        { name: 'Academic Focus', count: 3, pct: 21.43 }, { name: 'Teaching Methodology', count: 2, pct: 14.29 },
      ],
      improvements: [
        { name: 'Depth of Teaching', count: 11, pct: 29.73 }, { name: 'Exam Preparedness', count: 10, pct: 27.03 },
        { name: 'Assessments & Feedback', count: 7, pct: 18.92 }, { name: 'Study Discipline', count: 9, pct: 24.32 },
      ],
    },
    ppG9G12: {
      gradeSatisfaction: [
        { grade: 'Grade 9',  academic: 3.33, teaching: 4.00, gaps: 4.00 },
        { grade: 'Grade 10', academic: 3.25, teaching: 3.00, gaps: 3.25 },
        { grade: 'Grade 11', academic: 3.00, teaching: 3.00, gaps: 3.50 },
      ],
      academicPriorities: [
        { name: 'Board Results', count: 9, pct: 39.13 }, { name: 'Career Guidance', count: 5, pct: 21.74 },
        { name: 'Competitive Exams', count: 4, pct: 17.39 }, { name: 'Concept Mastery', count: 5, pct: 21.74 },
      ],
      stemPrograms: [
        { name: 'Advanced Coding', count: 6, pct: 33.33 }, { name: 'Design Thinking', count: 6, pct: 33.33 },
        { name: 'Robotics', count: 3, pct: 16.67 }, { name: 'Portfolio Projects', count: 3, pct: 16.67 },
      ],
    },
  },

  Dindigul: {
    label: 'Dindigul Report',
    cocurricular: [
      { name: 'Storytelling', count: 27, pct: 22.13 },
      { name: 'Dance & Movement', count: 25, pct: 20.49 },
      { name: 'Music & Rhythm', count: 20, pct: 16.39 },
      { name: 'Art & Craft', count: 17, pct: 13.93 },
      { name: 'Gardening', count: 13, pct: 10.66 },
      { name: 'DIY & Craft', count: 12, pct: 9.84 },
      { name: 'Pottery', count: 8, pct: 6.56 },
    ],
    academicFocus: [
      { name: 'Confidence & Expression', count: 29, pct: 35.80 },
      { name: 'Language Development', count: 26, pct: 32.10 },
      { name: 'Learning Through Play', count: 14, pct: 17.28 },
      { name: 'Early Numeracy', count: 12, pct: 14.81 },
    ],
    areasOfImprovement: [
      { name: 'Communication w/ Parents', count: 20, pct: 31.25 },
      { name: 'Individual Attention', count: 18, pct: 28.13 },
      { name: 'Activity-Based Learning', count: 14, pct: 21.88 },
      { name: 'Classroom Discipline', count: 6, pct: 9.38 },
      { name: 'Teaching Approach', count: 6, pct: 9.38 },
    ],
    satisfactionAreas: [
      { area: 'Student Motivation', count: 36, pct: 28.35 },
      { area: 'Teaching Quality', count: 28, pct: 22.05 },
      { area: 'Homework & Practice', count: 23, pct: 18.11 },
      { area: 'Doubt-Solving', count: 20, pct: 15.75 },
      { area: 'Assessments & Feedback', count: 20, pct: 15.75 },
    ],
    gradeSatisfaction: [
      { grade: 'Grade 1', academic: 3.60, teaching: 3.33, gaps: 3.20 },
      { grade: 'Grade 2', academic: 3.64, teaching: 3.59, gaps: 3.50 },
      { grade: 'Grade 3', academic: 2.83, teaching: 2.33, gaps: 3.00 },
      { grade: 'Grade 4', academic: 3.00, teaching: 3.50, gaps: 3.00 },
      { grade: 'Grade 5', academic: 2.50, teaching: 1.50, gaps: 1.00 },
    ],
    subjects: [
      { name: 'Mathematics', count: 43, pct: 34.68 },
      { name: 'Science', count: 29, pct: 23.39 },
      { name: 'Languages', count: 26, pct: 20.97 },
      { name: 'English', count: 26, pct: 20.97 },
    ],
    activities: [
      { name: 'Sports', count: 44, pct: 38.60 },
      { name: 'Dance', count: 27, pct: 23.68 },
      { name: 'Music', count: 22, pct: 19.30 },
      { name: 'Theatre', count: 21, pct: 18.42 },
    ],
    remarks: [
      { name: 'None / Satisfied', count: 14, pct: 28.00 },
      { name: 'Academic Focus', count: 6, pct: 12.00 },
      { name: 'Teaching Methodology', count: 7, pct: 14.00 },
      { name: 'Teaching Quality', count: 9, pct: 18.00 },
      { name: 'Extra-curricular', count: 3, pct: 6.00 },
      { name: 'Individual Attention', count: 3, pct: 6.00 },
      { name: 'Communication & Presentation', count: 2, pct: 4.00 },
      { name: 'Progress Tracking', count: 1, pct: 2.00 },
      { name: 'Hygiene & Infra', count: 1, pct: 2.00 },
      { name: 'Others', count: 4, pct: 8.00 },
    ],
    ppG6G8: {
      total: 14,
      teacherKnowledge: [{ r: 2, n: 2 }, { r: 3, n: 4 }, { r: 4, n: 7 }, { r: 5, n: 1 }],
      doubtSolving:     [{ r: 2, n: 3 }, { r: 3, n: 3 }, { r: 4, n: 7 }, { r: 5, n: 1 }],
      academicRigor:    [{ r: 1, n: 1 }, { r: 3, n: 4 }, { r: 4, n: 9 }],
      nTagging: [
        { name: 'Teaching Quality', count: 5, pct: 35.71 }, { name: 'None', count: 4, pct: 28.57 },
        { name: 'Academic Focus', count: 3, pct: 21.43 }, { name: 'Teaching Methodology', count: 2, pct: 14.29 },
      ],
      improvements: [
        { name: 'Depth of Teaching', count: 11, pct: 29.73 }, { name: 'Exam Preparedness', count: 10, pct: 27.03 },
        { name: 'Assessments & Feedback', count: 7, pct: 18.92 }, { name: 'Study Discipline', count: 9, pct: 24.32 },
      ],
    },
    ppG9G12: {
      gradeSatisfaction: [
        { grade: 'Grade 9',  academic: 3.33, teaching: 4.00, gaps: 4.00 },
        { grade: 'Grade 10', academic: 3.25, teaching: 3.00, gaps: 3.25 },
        { grade: 'Grade 11', academic: 3.00, teaching: 3.00, gaps: 3.50 },
      ],
      academicPriorities: [
        { name: 'Board Results', count: 9, pct: 39.13 }, { name: 'Career Guidance', count: 5, pct: 21.74 },
        { name: 'Competitive Exams', count: 4, pct: 17.39 }, { name: 'Concept Mastery', count: 5, pct: 21.74 },
      ],
      stemPrograms: [
        { name: 'Advanced Coding', count: 6, pct: 33.33 }, { name: 'Design Thinking', count: 6, pct: 33.33 },
        { name: 'Robotics', count: 3, pct: 16.67 }, { name: 'Portfolio Projects', count: 3, pct: 16.67 },
      ],
    },
  },
};
