// Survey data organised by school → grade band
// Source: Google Sheet 1f2q_axZPtfNcuWKIRT3yV6_WQhj44-bjS7RI2Cm1MAk
// Tabs: Pre-Primary · G1-G5 · G6-G8 · G9-G10

export const SCHOOLS = ['JPS', 'Tatva', 'Siddhanta', 'Arkere', 'Marathalli', 'HSR', 'Oragadam', 'Dindigul'];

export const SURVEY_DATA = {
  JPS: {
    label: 'JPS',
    prePrimary: {
      cocurricular: [
        { name: 'Dance & movement', n: 33 },
        { name: 'Art & craft', n: 32 },
        { name: 'Storytelling', n: 31 },
        { name: 'Music & rhythm', n: 24 },
        { name: 'DIY & craft', n: 21 },
        { name: 'Gardening', n: 16 },
      ],
      academicFocus: [
        { name: 'Confidence & expression', n: 42 },
        { name: 'Language development', n: 38 },
        { name: 'Learning through play', n: 32 },
        { name: 'Early numeracy', n: 16 },
      ],
      areasOfImprovement: [
        { name: 'Activity-based learning', n: 39 },
        { name: 'Individual attention', n: 27 },
        { name: 'Teaching approach', n: 15 },
        { name: 'Classroom discipline', n: 14 },
        { name: 'Communication with parents', n: 13 },
      ],
    },
    g1g5: {
      areas: [
        { name: 'Student motivation', n: 68 },
        { name: 'Teaching quality', n: 62 },
        { name: 'Homework & practice', n: 57 },
        { name: 'Doubt-solving', n: 54 },
        { name: 'Assessments & feedback', n: 39 },
      ],
      grades: [
        { grade: 'Grade 1', academicStd: 3.24, teachingQuality: 3.21, learningGaps: 3.12 },
        { grade: 'Grade 2', academicStd: 3.94, teachingQuality: 3.89, learningGaps: 3.94 },
        { grade: 'Grade 3', academicStd: 3.47, teachingQuality: 3.53, learningGaps: 3.40 },
        { grade: 'Grade 4', academicStd: 3.41, teachingQuality: 3.45, learningGaps: 3.23 },
        { grade: 'Grade 5', academicStd: 3.47, teachingQuality: 3.35, learningGaps: 3.19 },
      ],
      subjects: [
        { name: 'Mathematics', n: 16 },
        { name: 'Science', n: 14 },
        { name: 'Languages', n: 14 },
        { name: 'English', n: 12 },
      ],
      activities: [
        { name: 'Sports', n: 40 },
        { name: 'Dance', n: 26 },
        { name: 'Music', n: 22 },
        { name: 'Theatre', n: 20 },
      ],
      remarks: [
        { name: 'None', n: 68 },
        { name: 'Teaching quality', n: 15 },
        { name: 'Teaching methodology', n: 9 },
        { name: 'Progress tracking', n: 5 },
        { name: 'Hygiene', n: 4 },
        { name: 'Individual attention', n: 3 },
        { name: 'Academic Focus', n: 2 },
        { name: 'Fees', n: 2 },
        { name: 'Want in person meeting', n: 1 },
      ],
    },
    g6g8: {
      teacherKnowledge: [{ r: 1, n: 3 }, { r: 2, n: 5 }, { r: 3, n: 13 }, { r: 4, n: 8 }, { r: 5, n: 6 }],
      doubtSolving:     [{ r: 1, n: 4 }, { r: 2, n: 6 }, { r: 3, n: 11 }, { r: 4, n: 6 }, { r: 5, n: 8 }],
      academicRigor:    [{ r: 1, n: 4 }, { r: 2, n: 4 }, { r: 3, n: 15 }, { r: 4, n: 6 }, { r: 5, n: 6 }],
      majorIssues: [
        { name: 'None', n: 12 },
        { name: 'Teaching Quality', n: 8 },
        { name: 'Teaching methodology', n: 6 },
        { name: 'Individual Attention', n: 3 },
        { name: 'Academic Focus', n: 3 },
        { name: 'Progress Tracking', n: 1 },
        { name: 'Hygiene & Infra', n: 1 },
        { name: 'Others', n: 1 },
      ],
      areasOfImprovement: [
        { name: 'Depth of teaching', n: 11 },
        { name: 'Study discipline', n: 10 },
        { name: 'Assessments & feedback', n: 8 },
        { name: 'Exam preparedness', n: 6 },
      ],
    },
  },

  Tatva: {
    label: 'Tatva',
    prePrimary: {
      cocurricular: [
        { name: 'Music & rhythm', n: 14 },
        { name: 'Dance & movement', n: 12 },
        { name: 'Art & craft', n: 11 },
        { name: 'Gardening', n: 11 },
        { name: 'Storytelling', n: 9 },
        { name: 'DIY & craft', n: 8 },
        { name: 'Pottery', n: 5 },
      ],
      academicFocus: [
        { name: 'Confidence & expression', n: 14 },
        { name: 'Learning through play', n: 14 },
        { name: 'Language development', n: 9 },
        { name: 'Early numeracy', n: 4 },
      ],
      areasOfImprovement: [
        { name: 'Activity-based learning', n: 11 },
        { name: 'Individual attention', n: 9 },
        { name: 'Teaching approach', n: 5 },
        { name: 'Communication with parents', n: 5 },
        { name: 'Classroom discipline', n: 4 },
      ],
    },
    g1g5: {
      areas: [
        { name: 'Student motivation', n: 30 },
        { name: 'Teaching quality', n: 29 },
        { name: 'Doubt-solving', n: 23 },
        { name: 'Homework & practice', n: 20 },
        { name: 'Assessments & feedback', n: 19 },
      ],
      grades: [
        { grade: 'Grade 1', academicStd: 4.10, teachingQuality: 4.20, learningGaps: 4.00 },
        { grade: 'Grade 2', academicStd: 4.00, teachingQuality: 4.10, learningGaps: 4.10 },
        { grade: 'Grade 3', academicStd: 3.09, teachingQuality: 3.09, learningGaps: 2.64 },
        { grade: 'Grade 4', academicStd: 3.17, teachingQuality: 3.17, learningGaps: 2.33 },
        { grade: 'Grade 5', academicStd: 3.10, teachingQuality: 2.91, learningGaps: 2.64 },
      ],
      subjects: [
        { name: 'Mathematics', n: 33 },
        { name: 'Science', n: 33 },
        { name: 'Languages', n: 31 },
        { name: 'English', n: 22 },
      ],
      activities: [
        { name: 'Sports', n: 44 },
        { name: 'Dance', n: 23 },
        { name: 'Music', n: 23 },
        { name: 'Theatre', n: 20 },
      ],
      remarks: [
        { name: 'None', n: 25 },
        { name: 'Teaching Quality', n: 8 },
        { name: 'Academic Focus', n: 6 },
        { name: 'Others', n: 6 },
        { name: 'Teaching methodology', n: 5 },
        { name: 'Extra-curricular', n: 1 },
      ],
    },
    g6g8: {
      teacherKnowledge: [{ r: 1, n: 1 }, { r: 2, n: 7 }, { r: 3, n: 7 }, { r: 4, n: 15 }, { r: 5, n: 6 }],
      doubtSolving:     [{ r: 1, n: 2 }, { r: 2, n: 3 }, { r: 3, n: 9 }, { r: 4, n: 13 }, { r: 5, n: 10 }],
      academicRigor:    [{ r: 1, n: 1 }, { r: 2, n: 4 }, { r: 3, n: 10 }, { r: 4, n: 15 }, { r: 5, n: 8 }],
      majorIssues: [
        { name: 'None', n: 24 },
        { name: 'Teaching methodology', n: 5 },
        { name: 'Individual Attention', n: 3 },
        { name: 'Teaching Quality', n: 2 },
        { name: 'Progress Tracking', n: 2 },
        { name: 'Academic Focus', n: 1 },
        { name: 'Others', n: 1 },
      ],
      areasOfImprovement: [
        { name: 'Study discipline', n: 20 },
        { name: 'Exam preparedness', n: 14 },
        { name: 'Depth of teaching', n: 13 },
        { name: 'Assessments & feedback', n: 12 },
      ],
    },
    g9g10: {
      grades: [
        { grade: 'Grade 9',  boardPrep: 3.38, teachingQuality: 3.00, timeManagement: 3.54 },
        { grade: 'Grade 10', boardPrep: 3.00, teachingQuality: 3.00, timeManagement: 3.00 },
        { grade: 'Grade 12', boardPrep: 3.00, teachingQuality: 4.00, timeManagement: 4.00 },
      ],
      majorIssues: [
        { name: 'None', n: 15 },
        { name: 'Teaching methodology', n: 7 },
        { name: 'Academic Focus', n: 6 },
        { name: 'Individual Attention', n: 1 },
        { name: 'Others', n: 1 },
      ],
      academicPriorities: [
        { name: 'Board results', n: 14 },
        { name: 'Career guidance', n: 14 },
        { name: 'Concept mastery', n: 13 },
        { name: 'Competitive exams', n: 10 },
      ],
    },
  },

  Siddhanta: {
    label: 'Siddhanta',
    prePrimary: {
      cocurricular: [
        { name: 'Music & rhythm', n: 11 },
        { name: 'Dance & movement', n: 10 },
        { name: 'Storytelling', n: 10 },
        { name: 'Art & craft', n: 9 },
        { name: 'DIY & craft', n: 9 },
        { name: 'Gardening', n: 7 },
        { name: 'Pottery', n: 3 },
      ],
      academicFocus: [
        { name: 'Confidence & expression', n: 17 },
        { name: 'Language development', n: 9 },
        { name: 'Learning through play', n: 8 },
        { name: 'Early numeracy', n: 6 },
      ],
      areasOfImprovement: [
        { name: 'Individual attention', n: 11 },
        { name: 'Activity-based learning', n: 7 },
        { name: 'Teaching approach', n: 1 },
        { name: 'Classroom discipline', n: 1 },
      ],
    },
    g1g5: {
      areas: [
        { name: 'Student motivation', n: 31 },
        { name: 'Homework & practice', n: 20 },
        { name: 'Teaching quality', n: 17 },
        { name: 'Assessments & feedback', n: 17 },
        { name: 'Doubt-solving', n: 15 },
      ],
      grades: [
        { grade: 'Grade 1', academicStd: 4.11, teachingQuality: 3.94, learningGaps: 4.00 },
        { grade: 'Grade 2', academicStd: 3.29, teachingQuality: 3.29, learningGaps: 3.00 },
        { grade: 'Grade 3', academicStd: 3.90, teachingQuality: 3.90, learningGaps: 3.70 },
        { grade: 'Grade 4', academicStd: 3.90, teachingQuality: 3.90, learningGaps: 3.50 },
        { grade: 'Grade 5', academicStd: 4.18, teachingQuality: 3.75, learningGaps: 3.58 },
      ],
      subjects: [
        { name: 'Mathematics', n: 36 },
        { name: 'Languages', n: 35 },
        { name: 'Science', n: 27 },
        { name: 'English', n: 17 },
      ],
      activities: [
        { name: 'Sports', n: 48 },
        { name: 'Music', n: 32 },
        { name: 'Dance', n: 29 },
        { name: 'Theatre', n: 20 },
      ],
      remarks: [
        { name: 'None', n: 47 },
        { name: 'Teaching Quality', n: 4 },
        { name: 'Academic Focus', n: 4 },
        { name: 'Teaching methodology', n: 3 },
        { name: 'Others', n: 3 },
        { name: 'Extra-curricular', n: 2 },
        { name: 'Individual Attention', n: 2 },
      ],
    },
    g6g8: {
      teacherKnowledge: [{ r: 3, n: 2 }, { r: 4, n: 1 }, { r: 5, n: 2 }],
      doubtSolving:     [{ r: 3, n: 3 }, { r: 4, n: 1 }, { r: 5, n: 1 }],
      academicRigor:    [{ r: 3, n: 1 }, { r: 4, n: 3 }, { r: 5, n: 1 }],
      majorIssues: [
        { name: 'None', n: 2 },
        { name: 'Academic Focus', n: 1 },
      ],
      areasOfImprovement: [
        { name: 'Depth of teaching', n: 3 },
        { name: 'Exam preparedness', n: 2 },
      ],
    },
  },

  Arkere: {
    label: 'Arkere',
    prePrimary: {
      cocurricular: [
        { name: 'Dance & movement', n: 3 },
        { name: 'Storytelling', n: 1 },
        { name: 'Art & craft', n: 0 },
        { name: 'DIY & craft', n: 0 },
        { name: 'Gardening', n: 0 },
        { name: 'Music & rhythm', n: 0 },
      ],
      academicFocus: [
        { name: 'Language development', n: 2 },
        { name: 'Confidence & expression', n: 1 },
        { name: 'Learning through play', n: 1 },
        { name: 'Early numeracy', n: 0 },
      ],
      areasOfImprovement: [
        { name: 'Teaching approach', n: 3 },
        { name: 'Activity-based learning', n: 1 },
        { name: 'Individual attention', n: 1 },
        { name: 'Classroom discipline', n: 0 },
        { name: 'Communication with parents', n: 0 },
      ],
    },
    g1g5: {
      areas: [
        { name: 'Student motivation', n: 6 },
        { name: 'Assessments & feedback', n: 6 },
        { name: 'Teaching quality', n: 4 },
        { name: 'Homework & practice', n: 4 },
      ],
      grades: [
        { grade: 'Grade 1', academicStd: 3.75, teachingQuality: 4.00, learningGaps: 3.00 },
        { grade: 'Grade 2', academicStd: 3.50, teachingQuality: 4.00, learningGaps: 3.50 },
        { grade: 'Grade 3', academicStd: 4.29, teachingQuality: 3.57, learningGaps: 3.57 },
        { grade: 'Grade 5', academicStd: 3.00, teachingQuality: 3.00, learningGaps: 3.00 },
      ],
      subjects: [
        { name: 'Languages', n: 9 },
        { name: 'English', n: 8 },
        { name: 'Mathematics', n: 6 },
        { name: 'Science', n: 3 },
      ],
      activities: [
        { name: 'Sports', n: 11 },
        { name: 'Dance', n: 6 },
        { name: 'Music', n: 5 },
        { name: 'Theatre', n: 1 },
      ],
      remarks: [
        { name: 'None', n: 10 },
        { name: 'Individual attention', n: 2 },
        { name: 'Others', n: 2 },
      ],
    },
    g6g8: {
      teacherKnowledge: [{ r: 2, n: 2 }, { r: 3, n: 3 }, { r: 4, n: 20 }, { r: 5, n: 5 }],
      doubtSolving:     [{ r: 2, n: 1 }, { r: 3, n: 3 }, { r: 4, n: 2 }, { r: 5, n: 2 }],
      academicRigor:    [{ r: 3, n: 3 }, { r: 4, n: 4 }, { r: 5, n: 1 }],
      majorIssues: [
        { name: 'None', n: 4 },
        { name: 'Teaching methodology', n: 3 },
        { name: 'Communication & presentation', n: 1 },
      ],
      areasOfImprovement: [
        { name: 'Depth of teaching', n: 5 },
        { name: 'Assessments & feedback', n: 4 },
        { name: 'Study discipline', n: 3 },
        { name: 'Exam preparedness', n: 0 },
      ],
    },
  },

  Marathalli: {
    label: 'Marathalli',
    prePrimary: {
      cocurricular: [
        { name: 'Art & craft', n: 3 },
        { name: 'Dance & movement', n: 3 },
        { name: 'Storytelling', n: 3 },
        { name: 'DIY & craft', n: 0 },
        { name: 'Gardening', n: 0 },
        { name: 'Music & rhythm', n: 0 },
      ],
      academicFocus: [
        { name: 'Learning through play', n: 4 },
        { name: 'Confidence & expression', n: 3 },
        { name: 'Language development', n: 3 },
        { name: 'Early numeracy', n: 1 },
      ],
      areasOfImprovement: [
        { name: 'Activity-based learning', n: 3 },
        { name: 'Individual attention', n: 3 },
        { name: 'Teaching approach', n: 3 },
        { name: 'Classroom discipline', n: 1 },
        { name: 'Communication with parents', n: 0 },
      ],
    },
    g1g5: {
      areas: [
        { name: 'Student motivation', n: 23 },
        { name: 'Teaching quality', n: 21 },
        { name: 'Doubt-solving', n: 19 },
        { name: 'Homework & practice', n: 18 },
        { name: 'Assessments & feedback', n: 18 },
      ],
      grades: [
        { grade: 'Grade 1', academicStd: 4.00, teachingQuality: 4.00, learningGaps: 4.00 },
        { grade: 'Grade 2', academicStd: 3.50, teachingQuality: 4.00, learningGaps: 3.00 },
        { grade: 'Grade 3', academicStd: 3.00, teachingQuality: 3.00, learningGaps: 2.00 },
        { grade: 'Grade 4', academicStd: 3.50, teachingQuality: 3.33, learningGaps: 3.00 },
        { grade: 'Grade 5', academicStd: 3.00, teachingQuality: 3.00, learningGaps: 2.00 },
      ],
      subjects: [
        { name: 'Mathematics', n: 21 },
        { name: 'Languages', n: 20 },
        { name: 'Science', n: 19 },
        { name: 'English', n: 16 },
      ],
      activities: [
        { name: 'Sports', n: 25 },
        { name: 'Dance', n: 19 },
        { name: 'Music', n: 13 },
        { name: 'Theatre', n: 9 },
      ],
      remarks: [
        { name: 'None', n: 12 },
        { name: 'Teaching Quality', n: 7 },
        { name: 'Teaching methodology', n: 5 },
        { name: 'Extra-curricular', n: 2 },
        { name: 'Hygiene & Infra', n: 1 },
        { name: 'Individual Attention', n: 1 },
        { name: 'Others', n: 1 },
      ],
    },
    g6g8: {
      teacherKnowledge: [{ r: 1, n: 3 }, { r: 2, n: 5 }, { r: 3, n: 13 }, { r: 4, n: 8 }, { r: 5, n: 6 }],
      doubtSolving:     [{ r: 1, n: 4 }, { r: 2, n: 6 }, { r: 3, n: 11 }, { r: 4, n: 6 }, { r: 5, n: 8 }],
      academicRigor:    [{ r: 1, n: 4 }, { r: 2, n: 4 }, { r: 3, n: 15 }, { r: 4, n: 6 }, { r: 5, n: 6 }],
      majorIssues: [
        { name: 'None', n: 12 },
        { name: 'Teaching Quality', n: 8 },
        { name: 'Teaching methodology', n: 6 },
        { name: 'Individual Attention', n: 3 },
        { name: 'Academic Focus', n: 3 },
        { name: 'Progress Tracking', n: 1 },
        { name: 'Hygiene & Infra', n: 1 },
        { name: 'Others', n: 1 },
      ],
      areasOfImprovement: [
        { name: 'Depth of teaching', n: 11 },
        { name: 'Study discipline', n: 10 },
        { name: 'Assessments & feedback', n: 8 },
        { name: 'Exam preparedness', n: 6 },
      ],
    },
    g9g10: {
      grades: [
        { grade: 'Grade 9',  boardPrep: 3.00, teachingQuality: 3.00, timeManagement: 3.50 },
        { grade: 'Grade 10', boardPrep: 2.00, teachingQuality: 1.00, timeManagement: 1.00 },
      ],
      majorIssues: [
        { name: 'Academic Focus', n: 1 },
        { name: 'Individual Attention', n: 1 },
        { name: 'Teaching methodology', n: 1 },
      ],
      academicPriorities: [
        { name: 'Career guidance', n: 3 },
        { name: 'Competitive exams', n: 2 },
        { name: 'Board results', n: 1 },
        { name: 'Concept mastery', n: 1 },
      ],
    },
  },

  HSR: {
    label: 'HSR',
    prePrimary: {
      cocurricular: [
        { name: 'Dance & movement', n: 33 },
        { name: 'Art & craft', n: 32 },
        { name: 'Storytelling', n: 31 },
        { name: 'Music & rhythm', n: 24 },
        { name: 'DIY & craft', n: 21 },
        { name: 'Gardening', n: 16 },
      ],
      academicFocus: [
        { name: 'Confidence & expression', n: 42 },
        { name: 'Language development', n: 38 },
        { name: 'Learning through play', n: 32 },
        { name: 'Early numeracy', n: 16 },
      ],
      areasOfImprovement: [
        { name: 'Activity-based learning', n: 39 },
        { name: 'Individual attention', n: 27 },
        { name: 'Teaching approach', n: 15 },
        { name: 'Classroom discipline', n: 14 },
        { name: 'Communication with parents', n: 13 },
      ],
    },
    g1g5: {
      areas: [
        { name: 'Student motivation', n: 36 },
        { name: 'Teaching quality', n: 27 },
        { name: 'Homework & practice', n: 27 },
        { name: 'Doubt-solving', n: 26 },
        { name: 'Assessments & feedback', n: 22 },
      ],
      grades: [
        { grade: 'Grade 1', academicStd: 3.83, teachingQuality: 4.00, learningGaps: 4.00 },
        { grade: 'Grade 2', academicStd: 3.09, teachingQuality: 3.30, learningGaps: 3.20 },
        { grade: 'Grade 3', academicStd: 3.42, teachingQuality: 3.42, learningGaps: 3.25 },
        { grade: 'Grade 4', academicStd: 3.37, teachingQuality: 3.58, learningGaps: 3.37 },
        { grade: 'Grade 5', academicStd: 3.70, teachingQuality: 3.70, learningGaps: 3.60 },
      ],
      subjects: [
        { name: 'Mathematics', n: 16 },
        { name: 'Science', n: 14 },
        { name: 'Languages', n: 14 },
        { name: 'English', n: 12 },
      ],
      activities: [
        { name: 'Sports', n: 40 },
        { name: 'Dance', n: 26 },
        { name: 'Music', n: 22 },
        { name: 'Theatre', n: 20 },
      ],
      academicPriorities: [
        { name: 'Strong Math & Science foundation', n: 21 },
        { name: 'Concept clarity', n: 19 },
        { name: 'English communication', n: 17 },
        { name: 'Regular assessments', n: 13 },
      ],
      remarks: [
        { name: 'None', n: 68 },
        { name: 'Teaching quality', n: 15 },
        { name: 'Teaching methodology', n: 9 },
        { name: 'Progress tracking', n: 5 },
        { name: 'Hygiene', n: 4 },
        { name: 'Individual attention', n: 3 },
        { name: 'Academic Focus', n: 2 },
        { name: 'Fees', n: 2 },
        { name: 'Extra-curricular', n: 1 },
        { name: 'Want in person meeting', n: 1 },
      ],
    },
    g6g8: {
      teacherKnowledge: [{ r: 1, n: 3 }, { r: 2, n: 5 }, { r: 3, n: 13 }, { r: 4, n: 8 }, { r: 5, n: 6 }],
      doubtSolving:     [{ r: 1, n: 4 }, { r: 2, n: 6 }, { r: 3, n: 11 }, { r: 4, n: 6 }, { r: 5, n: 8 }],
      academicRigor:    [{ r: 1, n: 4 }, { r: 2, n: 4 }, { r: 3, n: 15 }, { r: 4, n: 6 }, { r: 5, n: 6 }],
      majorIssues: [
        { name: 'None', n: 12 },
        { name: 'Teaching Quality', n: 8 },
        { name: 'Teaching methodology', n: 6 },
        { name: 'Individual Attention', n: 3 },
        { name: 'Academic Focus', n: 3 },
        { name: 'Progress Tracking', n: 1 },
        { name: 'Hygiene & Infra', n: 1 },
        { name: 'Others', n: 1 },
      ],
      areasOfImprovement: [
        { name: 'Depth of teaching', n: 11 },
        { name: 'Study discipline', n: 10 },
        { name: 'Assessments & feedback', n: 8 },
        { name: 'Exam preparedness', n: 6 },
      ],
    },
    g9g10: {
      grades: [
        { grade: 'Grade 9',  boardPrep: 3.33, teachingQuality: 3.67, timeManagement: 3.00 },
        { grade: 'Grade 10', boardPrep: 3.33, teachingQuality: 2.67, timeManagement: 3.67 },
      ],
      majorIssues: [
        { name: 'Individual Attention', n: 2 },
        { name: 'Others', n: 2 },
        { name: 'Progress Tracking', n: 1 },
        { name: 'Teaching methodology', n: 1 },
      ],
      academicPriorities: [
        { name: 'Board results', n: 6 },
        { name: 'Concept mastery', n: 5 },
        { name: 'Competitive exams', n: 3 },
        { name: 'Career guidance', n: 2 },
      ],
    },
  },

  Oragadam: {
    label: 'Oragadam',
    prePrimary: {
      cocurricular: [
        { name: 'Dance & movement', n: 20 },
        { name: 'Music & rhythm', n: 19 },
        { name: 'Art & craft', n: 16 },
        { name: 'Storytelling', n: 14 },
        { name: 'Gardening', n: 12 },
        { name: 'DIY & craft', n: 9 },
        { name: 'Pottery', n: 9 },
      ],
      academicFocus: [
        { name: 'Confidence & expression', n: 21 },
        { name: 'Language development', n: 18 },
        { name: 'Learning through play', n: 15 },
        { name: 'Early numeracy', n: 9 },
      ],
      areasOfImprovement: [
        { name: 'Activity-based learning', n: 16 },
        { name: 'Classroom discipline', n: 11 },
        { name: 'Communication with parents', n: 10 },
        { name: 'Teaching approach', n: 9 },
        { name: 'Individual attention', n: 9 },
      ],
    },
    g1g5: {
      areas: [
        { name: 'Student motivation', n: 68 },
        { name: 'Teaching quality', n: 62 },
        { name: 'Homework & practice', n: 57 },
        { name: 'Doubt-solving', n: 54 },
        { name: 'Assessments & feedback', n: 39 },
      ],
      grades: [
        { grade: 'Grade 2', academicStd: 2.50, teachingQuality: 3.00, learningGaps: 2.50 },
        { grade: 'Grade 3', academicStd: 3.00, teachingQuality: 3.25, learningGaps: 3.50 },
        { grade: 'Grade 4', academicStd: 4.00, teachingQuality: 4.00, learningGaps: 4.00 },
        { grade: 'Grade 5', academicStd: 3.00, teachingQuality: 3.00, learningGaps: 3.00 },
      ],
      subjects: [
        { name: 'Mathematics', n: 24 },
        { name: 'English', n: 19 },
        { name: 'Science', n: 14 },
        { name: 'Languages', n: 14 },
      ],
      activities: [
        { name: 'Sports', n: 29 },
        { name: 'Dance', n: 14 },
        { name: 'Music', n: 11 },
        { name: 'Theatre', n: 5 },
      ],
      remarks: [
        { name: 'None', n: 18 },
        { name: 'Teaching methodology', n: 10 },
        { name: 'Academic Focus', n: 6 },
        { name: 'Teaching Quality', n: 5 },
        { name: 'Others', n: 4 },
        { name: 'Extra-curricular', n: 3 },
        { name: 'Hygiene & Infra', n: 3 },
        { name: 'Progress Tracking', n: 3 },
        { name: 'Individual Attention', n: 1 },
      ],
    },
    g6g8: {
      teacherKnowledge: [{ r: 3, n: 2 }, { r: 4, n: 8 }, { r: 5, n: 3 }],
      doubtSolving:     [{ r: 3, n: 6 }, { r: 4, n: 4 }, { r: 5, n: 3 }],
      academicRigor:    [{ r: 3, n: 7 }, { r: 4, n: 4 }, { r: 5, n: 2 }],
      majorIssues: [
        { name: 'None', n: 4 },
        { name: 'Extra-curricular', n: 3 },
        { name: 'Teaching Quality', n: 2 },
        { name: 'Teaching methodology', n: 2 },
        { name: 'Individual Attention', n: 1 },
        { name: 'Others', n: 1 },
      ],
      areasOfImprovement: [
        { name: 'Exam preparedness', n: 8 },
        { name: 'Depth of teaching', n: 6 },
        { name: 'Study discipline', n: 5 },
        { name: 'Assessments & feedback', n: 4 },
      ],
    },
    g9g10: {
      grades: [
        { grade: 'Grade 9',  boardPrep: 4.00, teachingQuality: 4.00, timeManagement: 4.00 },
        { grade: 'Grade 10', boardPrep: 2.50, teachingQuality: 2.00, timeManagement: 3.00 },
      ],
      majorIssues: [
        { name: 'None', n: 2 },
        { name: 'Others', n: 1 },
        { name: 'Teaching methodology', n: 1 },
      ],
      academicPriorities: [
        { name: 'Board results', n: 4 },
        { name: 'Concept mastery', n: 4 },
        { name: 'Career guidance', n: 4 },
        { name: 'Competitive exams', n: 1 },
      ],
    },
  },

  Dindigul: {
    label: 'Dindigul',
    prePrimary: {
      cocurricular: [
        { name: 'Storytelling', n: 27 },
        { name: 'Dance & movement', n: 25 },
        { name: 'Music & rhythm', n: 20 },
        { name: 'Art & craft', n: 17 },
        { name: 'Gardening', n: 13 },
        { name: 'DIY & craft', n: 12 },
        { name: 'Pottery', n: 8 },
      ],
      academicFocus: [
        { name: 'Confidence & expression', n: 29 },
        { name: 'Language development', n: 26 },
        { name: 'Learning through play', n: 14 },
        { name: 'Early numeracy', n: 12 },
      ],
      areasOfImprovement: [
        { name: 'Communication with parents', n: 20 },
        { name: 'Individual attention', n: 18 },
        { name: 'Activity-based learning', n: 14 },
        { name: 'Teaching approach', n: 6 },
        { name: 'Classroom discipline', n: 6 },
      ],
    },
    g1g5: {
      areas: [
        { name: 'Student motivation', n: 36 },
        { name: 'Teaching quality', n: 28 },
        { name: 'Homework & practice', n: 23 },
        { name: 'Doubt-solving', n: 20 },
        { name: 'Assessments & feedback', n: 20 },
      ],
      grades: [
        { grade: 'Grade 1', academicStd: 3.60, teachingQuality: 3.33, learningGaps: 3.20 },
        { grade: 'Grade 2', academicStd: 3.64, teachingQuality: 3.59, learningGaps: 3.50 },
        { grade: 'Grade 3', academicStd: 2.83, teachingQuality: 2.33, learningGaps: 3.00 },
        { grade: 'Grade 4', academicStd: 3.00, teachingQuality: 3.50, learningGaps: 3.00 },
        { grade: 'Grade 5', academicStd: 2.50, teachingQuality: 1.50, learningGaps: 1.00 },
      ],
      subjects: [
        { name: 'Mathematics', n: 43 },
        { name: 'Science', n: 29 },
        { name: 'English', n: 26 },
        { name: 'Languages', n: 26 },
      ],
      activities: [
        { name: 'Sports', n: 44 },
        { name: 'Dance', n: 27 },
        { name: 'Music', n: 22 },
        { name: 'Theatre', n: 21 },
      ],
      remarks: [
        { name: 'None', n: 14 },
        { name: 'Teaching Quality', n: 9 },
        { name: 'Teaching methodology', n: 7 },
        { name: 'Academic Focus', n: 6 },
        { name: 'Others', n: 4 },
        { name: 'Extra-curricular', n: 3 },
        { name: 'Individual Attention', n: 3 },
        { name: 'Communication & Presentation', n: 2 },
        { name: 'Hygiene & Infra', n: 1 },
        { name: 'Progress Tracking', n: 1 },
      ],
    },
    g6g8: {
      teacherKnowledge: [{ r: 2, n: 3 }, { r: 3, n: 3 }, { r: 4, n: 7 }, { r: 5, n: 1 }],
      doubtSolving:     [{ r: 2, n: 2 }, { r: 3, n: 4 }, { r: 4, n: 7 }, { r: 5, n: 1 }],
      academicRigor:    [{ r: 1, n: 1 }, { r: 3, n: 4 }, { r: 4, n: 9 }],
      majorIssues: [
        { name: 'Teaching Quality', n: 5 },
        { name: 'None', n: 4 },
        { name: 'Academic Focus', n: 3 },
        { name: 'Teaching methodology', n: 2 },
      ],
      areasOfImprovement: [
        { name: 'Depth of teaching', n: 11 },
        { name: 'Exam preparedness', n: 10 },
        { name: 'Study discipline', n: 9 },
        { name: 'Assessments & feedback', n: 7 },
      ],
    },
  },
};
